### ISSUE TITLE
Next planned release date

### ISSUE THREAD

**Issue by lucaswilric** [coreos/flannel#1063]
I'm wondering whether there's an expected date for the next release, and if so, what that date is.

## Context

My team is experiencing the SNAT race condition described in coreos#1004. Part of the fix for that problem is [merged](https://github.com/coreos/flannel/pull/1040) but not yet released, hence our curiosity.

**Comment by tomdee** [comment]
@rajatchopra and I are working on a release at the moment so expect something soon.

**Comment by toothbrush** [comment]
Hi again!  Just asking for your advice, not wanting to badger you.

Since we're experiencing this issue in our production systems, there's some pressure from rest of our team to move ahead before a real flannel release.  Our two options are:

* run `master` (which i lean towards), or
* cherry-pick the fix onto the release tag we're currently using in production, `v0.9.1`.

Can you see anything catastrophically bad about either of those options?  Either one sound preferable?  I don't want to be the guy who's nagging volunteer developers for free stuff, so, um, sorry if it sounds that way!

**Comment by rajatchopra** [comment]
@toothbrush Among the two options, I would pick the 'master' and freeze it.
Expect some action on the release this week though. Hopefully no more delays.

**Comment by rajatchopra** [comment]
Update: The release is blocked on certain PRs (#1061 and #1068). As soon as..

**Comment by toothbrush** [comment]
Cool, thanks for the progress report :)
