### ISSUE TITLE
Issue in getting flannel to work across multiple hosts(coreos cluster)

### ISSUE THREAD

**Issue by smakam** [coreos/flannel#112]
Hi
Sorry, if this is the wrong list to ask this question. I am trying to get flannel working across coreos cluster using the procedure specified in this link(https://github.com/coreos/flannel) and I am having some issues.

Following is my 3 node cluster:
core@core-01 ~/flannel $ fleetctl list-machines
MACHINE         IP              METADATA
52f5bf74...     172.17.8.103    -
8b3786a9...     172.17.8.102    -
ff59286c...     172.17.8.101    -

I did a basic test of etcd and fleet to make sure that they are working fine. 
I built flannel using the procedure specified in link above and pushed the networkconfig.

I pushed json networkconfig. I verified the networkconfig in all the hosts to make sure that they are synced up.
core@core-01 ~/flannel $ etcdctl get coreos.com/network/config

{
    "Network": "10.0.0.0/8",
    "SubnetLen": 20,
    "SubnetMin": "10.10.0.0",
    "SubnetMax": "10.99.0.0",
    "Backend": {
        "Type": "udp",
        "Port": 7890
    }
}

core@core-02 ~/flannel $ etcdctl get coreos.com/network/config

{
    "Network": "10.0.0.0/8",
    "SubnetLen": 20,
    "SubnetMin": "10.10.0.0",
    "SubnetMax": "10.99.0.0",
    "Backend": {
        "Type": "udp",
        "Port": 7890
    }
}

For some reason, I see that flannel is allocating the same IP address when I start a docker container on both hosts. I think thats because flannel is 1 host is not aware of the subnet that was allocated in other host. 

Output when flannel is started in host 1:
core@core-01 ~/flannel $ I0114 10:11:42.216702 01003 main.go:250] Installing signal handlers
I0114 10:11:42.216842 01003 main.go:119] Determining IP address of default interface
I0114 10:11:42.224256 01003 main.go:208] Using 10.0.2.15 as external interface
I0114 10:11:42.297606 01003 subnet.go:83] Subnet lease acquired: 10.10.192.0/20
I0114 10:11:42.300147 01003 main.go:218] UDP mode initialized
I0114 10:11:42.302223 01003 udp.go:239] Watching for new subnet leases

core@core-01 ~/flannel $ cat /run/flannel/subnet.env
FLANNEL_SUBNET=10.10.192.1/20
FLANNEL_MTU=1472

Output when flannel is started in host 2:
core@core-02 ~/flannel $ I0114 10:17:35.995527 02252 main.go:250] Installing signal handlers
I0114 10:17:35.995769 02252 main.go:119] Determining IP address of default interface
I0114 10:17:35.996421 02252 main.go:208] Using 10.0.2.15 as external interface
I0114 10:17:36.044919 02252 subnet.go:83] Subnet lease acquired: 10.10.192.0/20
I0114 10:17:36.050418 02252 main.go:218] UDP mode initialized
I0114 10:17:36.050569 02252 udp.go:239] Watching for new subnet leases

core@core-01 ~/flannel $ cat /run/flannel/subnet.env
FLANNEL_SUBNET=10.10.192.1/20
FLANNEL_MTU=1472

As per my understanding, subnet allocated must be different across hosts. Because of the above issue, when I start docker containers in both host, I see the same IP getting allocated and also the containers are not able to talk to each other.

I must be missing something basic here. Thanks in advance for any help on this.

Regards
Sreenivas

**Comment by smakam** [comment]
Forgot to provide info on my environment:
I am running coreos as a vagrant cluster on Windows machine with Virtualbox.

**Comment by eyakubovich** [comment]
@smakam This is becoming a common issue. I will need to add this to the README: https://github.com/coreos/flannel/issues/98

**Comment by smakam** [comment]
@eyakubovich 
Thanks for your response. It worked after I added the following option(-iface=eth1) to flannel start. Looks like this is specific to Vagrant environment. 
1 unrelated question:
Is flannel currently available only for CoreOS?

Thanks
Sreenivas

**Comment by kelseyhightower** [comment]
@smakam flannel should work on any platform.

**Comment by timechanter** [comment]
I running a small 3 node 557.1.0 cluster using flannel and have notice on many occasions restarting a host that the docker daemon will start running before flannel has completed its setup. This causes the docker0 interface to be the "normal" 172.x network instead of the desired 10.254.x network.

Looking at the journal I see etcd being delayed joining the cluster and flannel is thus delayed as it attempts to talk to etcd. Docker then starts up without waiting for flannel to be ready. The kibernetes boys use an etcd.waiter unit that their flannel depends on. Short of overriding the units for flannel and docker via cloud-init (im on AWS) is there anything I can do to avoid the race condition?

**Comment by timechanter** [comment]
In addition, restarting docker.service fails as it then discovers that the bridge it expects (10.254.x) is not the current docker0 bridge (172.x) . By deleting the docker0 interface first I can then restart docker and get the correct network configuration. Of course this kills all fleets on the node hard.

**Comment by eyakubovich** [comment]
@timechanter flannel does not wait for etcd in flannel.service since etcd does not support systemd notify for when it joins the cluster. Instead, flannel keeps trying to reach etcd on start up. While flannel supports notifying systemd when it's up, having docker.service depend on that doesn't work since not everyone wants to run flannel.

Therefore we suggest having flannel as the first entry listed in cloud-config's `units` list (https://coreos.com/docs/cluster-management/setup/flannel-config/). Since cloud-init will wait for the unit to start before proceeding to the next one, it should result in flannel fully starting before any docker containers come up. Docker itself starts on demand (socket activated), therefore it will also start after flannel is up.

However, there are cases when flannel can fail to start due to etcd. Either by timeout (I think around 1min) or because ExecStartPre fails (if you're using it to do `etcdctl`). This will make cloud-init proceed and probably results in what you're seeing.

There're two ways to fix this.
- Create docker.service drop-in to add a dependency on flannel (add `After=flanneld.service` and `Requires=flanneld.service`). Also add `Restart=always` or `Restart=on-failure`.

- In cloud-config, instead of using start command, use enable:
```
coreos:
  units:
    - name: flanneld.service
      command: enable
```
This will add flannel into `early-docker.target` and `docker.service` already has a dependency on that. The downside of this method, is it doesn't work on first-boot and you'll need to restart the machine after this ran once.

**Comment by timechanter** [comment]
@eyakubovich That worked an absolute treat. The following is what I added after flanneld.service for the interested.
```
    - name: docker.service
      drop-ins:
        - name: 60-docker-wait-for-flannel-config.conf
          content: |
            [Unit]
            After=flanneld.service
            Requires=flanneld.service
            Restart=always
            Restart=on-failure
      command: start
```

**Comment by eyakubovich** [comment]
@timechanter Glad to hear it worked. We will continue to explore how to better support in CoreOS out of the box. I realize that these hacks are not ideal.
