### ISSUE TITLE
Join network without reserving ip range

### ISSUE THREAD

**Issue by mikedanese** [coreos/flannel#113]
It would be nice to be able to have an option to run a flannel instance that makes the subnet routable but does not reserve a lease for itself. This would allow a box running a reverse proxy into the flannel network to route to ips on the flannel subnet without reserving an ip range. This is a pretty low priority feature but it would be quite useful.

**Comment by eyakubovich** [comment]
@mikedanese You may not need a whole range but I think you'll still need to get 1 IP to assign to the flannel interface. Otherwise what source IP will the other members of the flannel network see? Theoretically you _can_ have the source IP be of the external interface (e.g. eth0) and have the packet travel encapsulated through flannel. But it will result in asymmetric routing as the other way will cause the packet to travel directly via external interface un-encapsulated. But asymmetric routing just makes everything harder. There maybe some issues with ICMP as well.

On the other hand, it maybe just good to request a /32 instead of /24 (or whatever). In other words have the ability to allocate different size subnets to different hosts. This would be a very reasonable request but unfortunately seriously complicates not only allocation logic but also routing. By having all subnets of the same length, flannel doesn't have to do the usual longest prefix match and build trie, etc.

**Comment by mikedanese** [comment]
Thanks for the info. That makes a lot of sense. Maybe it will be easier in a latter iteration of Flannel. Feel free to close this.
