### ISSUE TITLE
SSH_CLIENT not set properly when using flannel

### ISSUE THREAD

**Issue by djannot** [coreos/flannel#117]
When I connect through ssh from a container to another using flannel, the SSH_CLIENT is set to the Subnet (10.0.94.0 33239 22) instead of the IP (should be 10.0.94.71 33239 22).

Also, when I run a netstat -an on the target container I see that the subnet is displayed:
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address               Foreign Address             State      
tcp        0      0 10.0.101.64:22              10.0.94.0:33239             ESTABLISHED 
tcp        0      0 10.0.101.64:22              10.0.94.0:45470             ESTABLISHED 

I understand that's probably because of the way flannel works, but I'd like to know if there's any workaround as it impacts a software I try to deploy and which is using this variable

Thanks

**Comment by eyakubovich** [comment]
@djannot The reason is that your IP is getting masqueraded by a rule that Docker has installed. If you're running Docker 1.3+, pass `--ip-masq=false` to docker daemon and `--ip-masq` to flanneld. This will tell Docker to not install IP Masquerading rules and flannel will install "proper" ones instead.

If you're using flannel with CoreOS that shipped it, it should happen automatically.

**Comment by djannot** [comment]
Thanks Eugene

I using the one from Google.
I'll build the one in github.
Why it's not part of the CoreOS binaries by default ?

**Comment by djannot** [comment]
This works perfectly. Thanks again

**Comment by eyakubovich** [comment]
@djannot flannel binaries are not in CoreOS due to our desire to keep base image small. But it's integrated into it and includes flanneld.service which pulls down flannel container when started.
