### ISSUE TITLE
Static ip

### ISSUE THREAD

**Issue by cdpb** [coreos/flannel#167]
Hi!

is it possible to add static ip's inside the flannel layer ?
I want to deploy a dns like skydns. The DNS has to be available from every node in the cluster but i don't want to bind it to a spezify host.

So maybe something like a new subnet ( /32 ? ), dynamicly assigned to a host which runs the container ( ExecPreStart ) ?

BR

cdpb

**Comment by eyakubovich** [comment]
@cdpb flannel doesn't have static reservations right now. One option is to register the DNS IP in etcd, then query it on the node and feed it into the container via env var:

`ExecStart=/bin/bash -c "dns=$(etcdctl get /someprefix/skydns) docker run --dns=$dns ..."`

**Comment by cdpb** [comment]
@eyakubovich thank you, should work :)

Just a idea: 

flannel watches etcd for changes, if a subnet gets provide my another machine, the routing set accordingly to etcd - so far so good. 
So e.g. I have a 10.0.1.0/24 registered to node1 till startup ( flannel overall network /8 )
A Container starts with: 

```
ExecPreStart=/usr/bin/etcdctl set /coreos.com/config/subnets/10.0.100-32
ExecStart=...docker run -p 10.0.100:53:53 ....
ExecStop=/usr/bin/etcdctl rm /coreos.com/config/subnets/10.0.100-32
```

So routing is done, the only missing part is a registered virtual ip to docker bridge, it should be really easy to realize.

**Comment by elephantfries** [comment]
I hope static-ip in flannel gets some traction.

Looking to etcd for flannel IP addresses is not ideal.  It requires exposing outer network to apps running in the flannel domain. If we do that, then we might as well expose flannel DNS to outer network and then find it through that network's static IP.  That's what our solution is.  This is far better then telling each application to watch etcd to see if anything's changed. It works but it's undesirable.  Apps running on the flannel network are not supposed to know there is some other network.

If static IP is too problematic, then at the very least, it would be nice if flannel would allocate the same IP address to a re-started container. It is smart enough to re-allocate the same subnet to a rebooted host.  Why cannot it do the same for the container??? (well, because it has no idea the newly started container is a restart of some previous container).  I realize, flannel cannot deduce it with current implementation.  Something needs to be added to flannel.

**Comment by eyakubovich** [comment]
@elephantfries I have a PR for subnet reservations almost ready. That will allow you to statically associate flannel subnet with the IP of the host interface. However something has to allocate the same IP from that subnet to the container -- and that something has to be the container runtime, like Docker.

Even if we were to support allocating /32 like @cdpb suggests, it would not work with Docker. I'm pretty sure Docker will fail if you specify `--bip=x.x.x.x/32`. But even if it didn't, it would limit your host to running one container. At this point you should just run this host without flannel -- let your DNS be on the "outer" network. If you're concerned about security policy, you can use iptables to restrict containers to just accessing flannel network and the DNS.

**Comment by elephantfries** [comment]
I see.  So looks like there is a need for an associated docker PR.

However I am after something slightly different.  I am OK with flannel randomly allocating subnets so long as it re-allocates the same subnet on the host reboot.  That is the behavior right now and that's fine.  I am after static allocation of IP addresses for containers on that subnet, or at least allowing a container regain its previous IP address upon (container) restart.  I realize flannel is lacking a hint to tell that a container wants the same IP address as allocated to some previous container.  Would allowing that require a docker PR or would it be possible to implement it entirely within flannel?

**Comment by eyakubovich** [comment]
@elephantfries It would need to be in Docker. flannel does not allocate IPs to containers. All flannel does is allocate a subnet and ensures that this subnet is routeable between other flannel subnets.

**Comment by elephantfries** [comment]
OK, thanks, looks like very high activity in this area in docker right now:

https://github.com/docker/libnetwork/issues/489

**Comment by qiukeren** [comment]
Request for this feature +1.
almost all thing can be done with domain name,
but DNS itself cannot escape from static IPs.

**Comment by tomdee** [comment]
Static subnet reservation for a host can be done following this doc I added https://github.com/coreos/flannel/blob/master/Documentation/reservations.md

Static IP addresses for individual containers/pods is not something to flannel manages.
