### ISSUE TITLE
similar problem like #111 Connect issues with flannel on Centos 6.

### ISSUE THREAD

**Issue by qihuagao** [coreos/flannel#180]
Reference: #111

I use an more older version: CentOS release 6.5 (Final)
This does not definitely happen, but is very likely.
I simply reviewed the code, and added some debug code in proxy.c:find_route, found this function wasn't called when I got "Invalid argument". So I guess perhaps tun_to_udp or tun has some problem to read the incoming data.  But really I can't well understand the structure of the code, so haven't dig more in the problem.
Can you help me troubleshoot the problem?  I have the same env like #111 except I use virtualbox. Please let me know if you want to know more info about this.

**Comment by eyakubovich** [comment]
@qihuagao It's hard for me to troubleshoot this as I failed to replicate it last time. However, my theory is that the kernel does not like the IP on flannel0. Say the flannel network is `10.1.0.0/16` and the host got allocated  `10.1.5.0/24`. `flannel0` gets assigned `10.1.5.0/16` and docker0 gets `10.1.5.1/24`. Technically `10.1.5.0/16` is a perfectly legal IP but I think because of docker0's /24 "overlaps", flannel0 IP, it randomly causes these problems.

Can you either delete flannel0's IP: `ip addr del 10.1.5.0/24 dev flannel0` or, if this doesn't work, give it some IP outside of the allocated subnet: `ip addr add 10.1.253.1/16` (just make sure .253 is unused). You will no longer be able to ping flannel0 on the remote host but it may solve the problem. It's not a solution but it will help us figure out if that's what's causing the problem.

**Comment by qihuagao** [comment]
Thank you for response.
I tried this:
 ifconfig docker0 down
 brctl delbr docker0
and then start docker after flanneld finish start.
It seems working, so I guess your analysis should be right. but not sure whether it can solve all occasions.

**Comment by CocaCola183** [comment]
@qihuagao save my life

**Comment by tomdee** [comment]
There is a fix in v0.7.0 which might help with this.

**Comment by tomdee** [comment]
I'm assuming that v0.7.0 resolved this so closing. Please reopen if you're still having problems.
