### ISSUE TITLE
Fix flannel subnet when it restarted

### ISSUE THREAD

**Issue by resouer** [coreos/flannel#205]
Hi guys,

we are using flannel as kubernetes minion's network, see https://github.com/ZJU-SEL/kube-in-docker/blob/master/minion.sh#L38

But we found that if we restarted the node, the FLANNEL_SUBNET will change, we have to reconfigure the DOCKER_OPTS and restart dockerd, is there any way to fix FLANNEL_SUBNET?

**Comment by eyakubovich** [comment]
@resouer flannel will reuse the same subnet if the IP of the host has not changed (since that's how it identifies the host). On a physical machine with DHCP, it will usually keep an IP and is fine. In a cloud environment, depending on the provider and how you restart the node, you may end up with a new IP.

However, you should add flannel as a dependency to docker and wait for it to write out `/run/flannel/subnet.env` before satisfying the dependency. If you're using systemd, set the service type to "notify" since flannel signals that it's READY to systemd only after it has written out the file. If you're using upstrart, I believe there's a way to emit a signal on file creation/change.

**Comment by resouer** [comment]
@eyakubovich It seems my flannel did not reuse the same subnet.

Before I restart flanneld:
```
root@ubuntu:/home/vcap# cat subnet.env 
FLANNEL_SUBNET=10.1.33.1/24
FLANNEL_MTU=1472
FLANNEL_IPMASQ=false
```
After I restart the flanneld:
```
root@ubuntu:/home/vcap# sudo -b docker -H unix:///var/run/docker-bootstrap.sock ps 
root@ubuntu:/home/vcap# CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS              PORTS               NAMES
fc346a53985d        wizardcxy/flannel:0.3.0   "/opt/bin/flanneld -   3 weeks ago         Up 25 minutes                           distracted_pike     

root@ubuntu:/home/vcap# sudo docker -H unix:///var/run/docker-bootstrap.sock cp fc346a53985d:/run/flannel/subnet.env .
root@ubuntu:/home/vcap# cat subnet.env 
FLANNEL_SUBNET=10.1.10.1/24
FLANNEL_MTU=1472
FLANNEL_IPMASQ=false
root@ubuntu:/home/vcap# source subnet.env 

```

It changed, then I have to reconfigure my docker opts to make it work.

Any tips?

**Comment by resouer** [comment]
ping @@eyakubovich any idea about this?

**Comment by eyakubovich** [comment]
@resouer Your approach seems fine although I prefer to have `/run/flannel/subnet.env` as a volume so it's easier to source in. Can you do the following steps:
1. Run flannel and acquire the lease. Say you get 10.1.10.1/24.
2. Look it up in etcd: `etcdctl get /coreos.com/network/subnets/10.1.10.1-24`.
3. Check the value of PublicIP. It should match that of `eth0`.
4. Restart flannel so it acquires a new lease and look it up in etcd again.

Please paste flannel logs to help us debug.

**Comment by resouer** [comment]
@eyakubovich I can not reproduce it now, flannel works well and reuse the subnet.

Is it possible that because my flannel has been stopped for too long time, after I start it again, it create a new subnet?

**Comment by eyakubovich** [comment]
@resouer Yes, flannel acquires a 24 hour lease and refreshes every 23 hours. So if flannel is stopped for more than 1 hour, there's a possibility of it loosing the lease. We can change it so that it refreshes every 12 hours but that will only increase the window. Once the lease is lost, a new one is acquired.

**Comment by resouer** [comment]
Thanks, issue closed!
