### ISSUE TITLE
Reaction to Canonical's Fan Networking concept

### ISSUE THREAD

**Issue by politician** [coreos/flannel#224]
> Fan trades access to one user-selected /8 (potentially external) address range for an expanded pool of “organisation-internal” addresses to be used by containers or virtual machines. Fan does this by mapping the addresses in a way that can be computed, rather than one that requires maintenance of distributed state (e.g., routing tables).

https://wiki.ubuntu.com/FanNetworking
HN - https://news.ycombinator.com/item?id=9764391

What is your opinion of this approach to container networking?

**Comment by eyakubovich** [comment]
I don't think there's one right way to do network virtualization -- they all end up being either complex or hacky, or both. That's why we need options. Having Fan's deterministic hashing removes the need for a control plane and persistence layer. But it also comes with limitations. For example, flannel stores more than just allocated subnets and mapped IPs in etcd. VXLAN backend stores VTEP MAC address and allows for running VXLAN without multicast (which actually is a huge simplification).
