### ISSUE TITLE
Reservation Mode

### ISSUE THREAD

**Issue by bcwaldon** [coreos/flannel#280]
I'd like to be able to run flannel in such a mode where each node blocks until a subnet has been allocated to it via the API. This means that the node is no longer responsible for allocating and maintaining a lease itself.

I have two functional requirements for this:
1. flannel nodes running in reservation mode block until a reservation is available - I don't want a race between the reservation being available in etcd and the node starting up
2. the flannel API must provide an endpoint that allows me to create and destroy reservations

I'm not sure what the behavior should be when a reservation is deleted

**Comment by bprashanth** [comment]
I solved a similar problem on Kubernetes with a proxy flannel server https://github.com/kubernetes/kubernetes/pull/13877. The flannel daemons block till the master assigns the node a subnet, @eyakubovich let me know if you're interested on collaborating to a similar end goal. With my patch, the flannel daemon can only read subnets, not create or destroy them.

**Comment by eyakubovich** [comment]
@bprashanth I actually have the PR for this ticket mostly done. It's being held up by a few things. First, the 2 refactoring PRs (#338 and #344), and then a patch to add lease revocations. The reservation in etcd is denoted by having the subnet node have a TTL=0 (no expiration). There's also a remote API calls for `AddReservation` and `RemoveReservation`. This does not make etcd read-only for flannel as it still has to set things like BackendData but with "flannel server" it is possible to gate the flannel daemons from the having general etcd access. Is that sufficient for your needs?

**Comment by bprashanth** [comment]
sounds like the proxy flannel server will still have to manage any persistence to etcd and redirect to apiserver. That's ok for node specific metadata (eg VTEP), not ok if it's going to delete a subnet from the global pool. IMO global resources should fall under the purview of the cluster manager, so as long as the daemon doesn't go mad if the flannel server no-ops a Delete/Add we should be ok. 

I actually don't need reservation mode currently because the daemon just hangs on /subnet/leases (whichever one of those endpoints it hits first) till the master tells it what subnet to use.

**Comment by eyakubovich** [comment]
There is no authorization per API call so a node could end up deleting a subnet. The server does need to have methods like "RevokeLease" or "SetNetworkConfig" but the question is who should be allowed to call that. I think we could add access control in the future to solve this problem.

**Comment by andrewkrug** [comment]
How do you use this feature?   It looks like it was merged without updating any docs.
