### ISSUE TITLE
Doc how to use Multi-network mode in Docker

### ISSUE THREAD

**Issue by resouer** [coreos/flannel#288]
As we already have https://github.com/coreos/flannel#multi-network-mode-experimental, we need to document how to use this in Docker.

My use case is: can we divide containers into groups and isolated with each other even they are on the same host?

**Comment by eyakubovich** [comment]
Good idea to document but let's brainstorm the best way to do that in these comments. My initial thought is to run multiple docker daemons. This way you can use `--bridge` arg to docker daemon to create multiple bridges.

Also note that multi-network support now does not really isolate the containers from each other on different networks. They can still cross-talk to each other although I would welcome PRs to add some iptables rules to firewall the networks from each other.

**Comment by resouer** [comment]
@eyakubovich interesting, then what's multi-network design for if not for isolate groups?

And I don't think start multiple dockerd is good, that will make clients complain. Maybe allocate hosts among the networks:
```
host 1:red
host2:blue
host3:red
```

**Comment by eyakubovich** [comment]
@resouer You can run multiple docker daemons if you point them to different unix sockets, data directory and pid file. The client can be told via `DOCKER_HOST` or `-H` which socket to use.

If you only need a host to join a single network, then you can definitely run just one docker daemon and then there should't be any cross talk (unless you're using `aws-vpc` or `gce` backends).

Multi-network functionality is still limited because it's early. RedHat was planning to contribute an OVS backend that would operate at L2 and provide isolation.

**Comment by resouer** [comment]
Thanks for your reply. Any issue/pr about OVS backend progress?

I once used SocketPlane, but it's a pity that I found it's wrapping of OVS is buggy and that's why I turned to Flannel: much steady and easy to integrate with Docker/Kubernetes.

**Comment by tomdee** [comment]
Closing given #638
