### ISSUE TITLE
Flannel container should mount /etc/ssl/certs instead

### ISSUE THREAD

**Issue by vaijab** [coreos/flannel#302]
Recent version of flannel (0.5.3) switched to using a different etcd client library which checks whether TLS certs I assume. In my case, I have TLS configured everywhere, including etcd. I am using TLS certs signed with my own CA.

The CA cert is added via `write_files` to `/etc/ssl/certs` and `update-ca-certificates` is used to generate new `ca-certificates.crt` file.

Looking at `flannel.service` file, it seems to mount `/usr/share/ca-certificates` which does not contain my custom CA cert.

Shouldn't flannel mount `/etc/ssl/certs` instead?

**Comment by eyakubovich** [comment]
In CoreOS, `flanneld.service` pulls in `/usr/share/ca-certificates` for "well-known" certs (in practice it is needed to talk to AWS metadata service). Your custom ones should go into `/etc/ssl/etcd` on the host which also gets mapped into `/etc/ssl/etcd` in the container. So you should then use config-config's `coreos.flannel.etcd_certfile` and set it to `/etc/ssl/etcd/mycert.crt`. Same goes for `etcd_cafile` and `etcd_keyfile`. Let me know if it doesn't work.

Also, the _host_ location is configurable. Using flanneld.service drop-in, you can override it using `Environmnet="ETCD_SSL_DIR=/etc/ssl/certs"`. Just remember that the path inside the container is still going to be `/etc/ssl/etcd` so your paths in cloud-config will still need to use `/etc/ssl/etcd`.

**Comment by vaijab** [comment]
@eyakubovich thanks. That actually works. It is just a little annoying that I have to put CA cert in two different places on the host: `/etc/ssl/certs` and `/etc/ssl/etcd`.

I am going to close this one now.

**Comment by eyakubovich** [comment]
@vaijab Did you try the `ETCD_SSL_DIR` to override the path?

**Comment by vaijab** [comment]
@eyakubovich I just added CA cert to `/etc/ssl/etcd` and set `coreos.flannel.etcd_certfile` - that works well.

AFAIK go's TLS implementation looks in `/etc/ssl/certs` for CA certs by default, so it would make sense for flannel to just assume that custom CA certs live in `/etc/ssl/certs`, that's why I suggested flannel to mount `/etc/ssl/certs` as well.

**Comment by eyakubovich** [comment]
@vaijab You're definitely right but there's a technical issue doing it this way. Because CoreOS is shipped completely in `/usr`, `/etc/ssl/certs` has individual symlinks to certs in `/usr/share/ca-certificates`. The directory itself is not a symlink so you can place custom certs there.

But because flannel runs in a container, we actually can't mount host's `/etc/ssl/certs` into the container. It will result in broken links. Instead, we mount `/usr/share/ca-certificates` into container's `/etc/ssl/certs` and have to create a separate volume for the custom ones.

One workaround would have been to also mount `/usr/share/ca-certificates` into the container at the same path to keep the links working. Yet that also seems hacky.
