### ISSUE TITLE
Need ability to control leases from outside of flanneld

### ISSUE THREAD

**Issue by rajatchopra** [coreos/flannel#319]
Use case: in case of multiple networks, all hosts may not need a lease until they have a container running. Also, a lease may run out of addresses so another lease may be warranted at runtime.

Proposing a flannelctl/REST-API interface where the following APIs would exist:

| API | Args | Return object |
| --- | --- | --- |
| get_networks | - | [ ]Network |
| get_leases | network | [ ]Lease |
| create_lease | network | Lease |
| delete_lease | network, lease | - |

Thoughts? If there is no objection, I will put up a PR implementing this.

Attention: @eyakubovich @dcbw

**Comment by eyakubovich** [comment]
@rajatchopra Conceptually I don't have objections but I would like to figure out the following:
1. What uses this API? Currently the REST API is implemented by the server. If create_lease is called by someone (e.g. flannelctl), how does flanneld (in client mode) know that it needs to pick up this lease and run with it?
   - Side note: I'm working on reservations that will work as follows. The REST API has `AddReservation(subnet, publicIP)`, `DeleteReservations(subnet)` methods. When flanneld runs, it'll end up using the reservation and not a random subnet. I will also add a flag like `--reservations-only` that will cause flanneld to wait for reservations -- it won't acquire a lease if reservation is not there.
   - Can we use the above mechanism to have flanneld wait for `create_lease`?

2. I'm also almost done with RevokeLease PR. That call deletes the lease and flanneld will go back and try to acquire a lease. We can change the behavior of what happens when the lease is lost with some policy. We're actually going to be running it in combo with `--reservations-only`. What behavior would you like?

**Comment by rajatchopra** [comment]
@eyakubovich 
The APIs in the proposal were meant to be run on the client flanneld. So its a local API where a local container runtime/orchestrator (through CNI for example) will claim that it has run out of a network's current local lease and it needs a new one.
Without this, the method of obtaining lease is that a lease is obtained for all networks, whether a container will ever be born on that node or not.

On the new Reservation work, first of all, Add/Delete Reservation should include the network as an arg. The only question I have is who will really create the reservations? Does it become the responsibility of the API user to manage the subnet allocation then? What if there are clashes?

**Comment by eyakubovich** [comment]
First of all, Add/Delete Reservations definitely accept the network arg. My fault for not saying that. Second, I'm not really against flanneld (client mode) having an API but I just want to entertain the idea of communicating with it via etcd or server. So in the case of `create_lease`, if `/coreos.com/network/subnet/10.1.6.0-24` gets created with `PublicIP=192.168.5.6`, the node `192.168.5.6` notices it and "picks it up".

>On the new Reservation work, first of all, Add/Delete Reservation should include the network as an arg. The only question I have is who will really create the reservations? Does it become the responsibility of the API user to manage the subnet allocation then? What if there are clashes?

The reservations are meant to be added by the user via flannelctl or via an API to the server. If the current subnet is already in use by another node, the API call will fail.

**Comment by rajatchopra** [comment]
I think its ok to get the leases done and notified via etcd/server, although it seems like a circuitious method to achieve. We can always think of optimizing later.
For the AddReservation, can we pass an empty subnet, which will indicate flannel to check out a subnet from the network's pool automatically?

**Comment by eyakubovich** [comment]
I agree that going via etcd is kind of backwards on first glance. But there is a certain beauty in it as well -- we have this central store through which we coordinate (hello, Linda). You can manipulate everything with just "etcdctl" or any host can issue these requests to the flannel server. You will always be running flannel server, correct? If that's not the case, we'll need to have an API endpoint on the local flanneld.

AddReservation is done with a subnet node that has TTL=0 (i.e. no TTL). Recall that leases have a TTL set to 24 hrs.

**Comment by rajatchopra** [comment]
Yes we plan to run the server always. Could you confirm that we can have an AddReservation call with 'nil' subnet which will mean a subnet will automatically be allocated (and ttl set to 0 after that)?
Otherwise it seems that the caller has to do the subnet allocation.

**Comment by eyakubovich** [comment]
@rajatchopra `AddReservation` requires non-nil subnet in my current branch. But we would modify it (or create a new method) to take a nil subnet and allocate one. It would commit it as a reservation with no TTL. The downside of this is that it's a reservation -- it won't go away until explicitly deleted.

**Comment by dcbw** [comment]
Rajat touched on this in the initial comment, but our driver here is   In our case we want all the nodes to be aware of the network and Register it with the backend, but we don't actually want to obtain the lease or add a reservation until we know we're going to actually use it.  And that only happens through the CNI plugin, not through flanneld (becuase flanneld doesn't care about the actual containers, just the inter-node plumbing).

So the CNI plugin (or orchestrator like kubernetes/openshift) would be the thing calling flannelctl to allocate the network subnet lease *when the first pod is started on the node*.  Or the CNI plugin could hit up etcd I suppose, except that we'd rather use the flannel 'remote' functionality and have the server flanneld arbitrate access so that the nodes don't require write access to etcd.

So with your reservations code, would our CNI plugin then be expected to call AddReservation or AcquireLease itself against the server flanneld?

**Comment by eyakubovich** [comment]
@dcbw Yes, the CNI plugin would be calling `AddReservation(nil, myPublicIP)` against the server flanneld. I realize however now that there will be a race. AddReservation will probably return before client flanneld has picked up the reservation and ran with it. So while AddReservation can return the allocated subnet, you won't know that it's actually routable at this point. This might not be a big deal as even if you had `create_subnet` against the client flanneld on the host, you wouldn't know when the rest of the cluster saw the new subnet add made it routeable.

**Comment by tomdee** [comment]
Closing given #638
