### ISSUE TITLE
flannel0 network interface in aws-vpc backend

### ISSUE THREAD

**Issue by shayts7** [coreos/flannel#357]
Hi,

I'm not a network expert, so sorry ahead if my question is a basic one...
I noticed that when I use vxlan backend I can find flannel0 interface, but this interface does not exist when using aws-vpc (and still everything works just fine :-)).

Can someone explain that?

Thanks,
Shay

**Comment by eyakubovich** [comment]
Small nit: with vxlan, you should see `flannel.1` and not `flannel0` (that's for udp backend).

With `vxlan` (and `udp`) backends, flannel sets up encapsulation (where it wraps one packet in another). That's done by first routing those packets to this encapsulation interface (i.e. flannel.1) and then once it's wrapped it goes out the host interface (e.g. eth0).

With `aws-vpc` (and `gce`) backend, the packets go out of the host interface as is (unencapsulated). What that backend does is, using a REST API, configures the AWS VPC router to tell it how to route the packets with flannel IPs. Once the packets arrive at the destination host, they'll be directed to `docker0` bridge because Docker has set up a route for it.

**Comment by shayts7** [comment]
Thanks for the detailed explanation!
