### ISSUE TITLE
[question] Why use cgo to implement proxy in udp backend?

### ISSUE THREAD

**Issue by ranbochen** [coreos/flannel#368]
I'm reading flannel code to learn golang.
I found that udp backend is written in C.
Why not just use goroutine?  like: go func() { io.Copy(tun, udp) }
Can anyone explain this, thanks.

**Comment by eyakubovich** [comment]
It was to pick up a bit of performance. Since you would need two goroutines, one for each direction, it turns out that the context switching between them adds some overhead. So C version wins out.

However, this is probably irrelevant now as we have vxlan (kernel based) backend so anything that needs performance (which should be everything) can just use that.

**Comment by ranbochen** [comment]
Thank you for your answer.
I see a commit log here: https://github.com/coreos/flannel/commit/23c28ecee4059d5f18acfa271bf687fba8909058
