### ISSUE TITLE
flanneld should error if "SubnetMin" isn't on SubnetLen boundary

### ISSUE THREAD

**Issue by workhardcc** [coreos/flannel#430]
Hi everyone,
My subnet config in etcd as below:
`etcdctl get    /coreos.com/network/178/config
{"Network": "10.10.178.0/24", "SubnetLen": 26, "SubnetMin": "10.10.178.200", "SubnetMax": "10.10.178.253", "Backend": {"Type": "udp", "Port": 7890}}`
Firstly, `./flanneld --etcd-endpoints=http://10.10.78.14:4001 --networks=178 &`, docker host get a new nic named flannel0 has ip "10.10.178.200",that's correct!
Secondly, star docker daemon by `DOCKER_OPT_BIP="--bip=10.10.178.201/26"`,there is a new bridge named docker0 created, use ip 10.10.178.201.
At last, kubectl create new pod in this host, enter container there is a ip 10.10.178.193.
So, why container's ip  not 10.10.178.202 but 10.10.178.193.

> "SubnetMin": "10.10.178.200"

**Comment by tomdee** [comment]
Looks like the `--bip` option to Docker doesn't behave as expected - there's not much to go on at https://docs.docker.com/engine/reference/commandline/daemon/ but potentially the behaviour here has changed. It appears to be resolving to the /26 boundary and allocating from .193 rather than .202 as hoped.

One workaround might be to use CNI with kubernetes and the flannel CNI plugin.

**Comment by eyakubovich** [comment]
I would say that Docker does the right thing here by first masking the `--bip` value with the `/26` mask. I think flannel should error out in this case when `SubnetMin` is not at the `SubnetLen` boundary.
