### ISSUE TITLE
question about latest version of vxlan backend

### ISSUE THREAD

**Issue by jwfang** [coreos/flannel#810]
i am learning vxlan & flannel, and have some questions. hoping someone can clarify it for me. :)

1. about l2missing and l3 missing

   from https://github.com/coreos/flannel/blob/c1b6a064a3b839775efc908e97a0f5d8478f1fb9/backend/vxlan/vxlan.go#L21 it says ARP is l2missing, fdb is l3missing.
  but from https://www.slideshare.net/enakai/how-vxlan-works-on-linux it's the opposite;

2. *nexthop* and *onlink* in ip-route command

is the *nexthop* really necessary [here](https://github.com/coreos/flannel/blob/c1b6a064a3b839775efc908e97a0f5d8478f1fb9/dist/extension-vxlan#L8) ? it seems to be used for *multipath* routing, but for flannel, there is only on path, right ?

from *ip-route* manual,
> onlink pretend that the nexthop is directly attached to this link, even if it does not match any interface prefix. 

also i guess the *flannel-vxlan* dev would match the target address, should we need *onlink* ?

there is no lastest flannel image from https://quay.io/repository/coreos/flannel , so i may need to build my own to test against it.

**Comment by tomdee** [comment]
I'll do my best to answer these questions, but happy to get input from others too
1) I may have gotten these the wrong way round. But since they're now removed I'm not going to think about it too hard!
2) Good spot! I think I must have misread the man page
>INFO_SPEC := NH OPTIONS FLAGS [ nexthop NH ] ...
>       NH := [ via [ FAMILY ] ADDRESS ] [ dev STRING ] [ weight NUMBER ]
>               NHFLAGS
So I don't think nexthop is needed but `onlink` is needed.

See here for details on getting master builds - https://github.com/coreos/flannel/blob/master/Documentation/building.md#obtaining-master-builds

But note - there's a v0.9.0-rc1 build available now too.
