### ISSUE TITLE
Error registering network: failed to acquire lease: node.

### ISSUE THREAD

**Issue by mendoncangelo** [coreos/flannel#993]
Started a Ubuntu 16.04 Box with Kubernetes 1.10. Installed Docker, Kubelet, Kubectl and Kubeadm. Install Flannel using the kubectl command provided in the github readme.md for flannel. Restarted the master node and got a new public IP address. 

## Expected Behavior
I would expect that the flannel pod would be running without any error after restarting the box.
However on restarting the node I get a new public IP address.
 Flannel container failing with the following error.
```
I0518 19:28:39.956871       1 main.go:475] Determining IP address of default interface
I0518 19:28:39.960552       1 main.go:488] Using interface with name eth0 and address 172.31.125.3
I0518 19:28:39.960615       1 main.go:505] Defaulting external address to interface address (172.31.125.3)
I0518 19:28:40.001370       1 kube.go:131] Waiting 10m0s for node controller to sync
I0518 19:28:40.001464       1 kube.go:294] Starting kube subnet manager
I0518 19:28:41.001666       1 kube.go:138] Node controller sync successful
I0518 19:28:41.001704       1 main.go:235] Created subnet manager: Kubernetes Subnet Manager - hostname.mylabserver.com
I0518 19:28:41.001710       1 main.go:238] Installing signal handlers
I0518 19:28:41.001884       1 main.go:353] Found network config - Backend type: vxlan
I0518 19:28:41.002001       1 vxlan.go:120] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
E0518 19:28:41.054404       1 main.go:280] Error registering network: failed to acquire lease: node "hostname.mylabserver.com" pod cidr not assigned
I0518 19:28:41.054432       1 main.go:333] Stopping shutdownHandler...
```

## Context
I am trying to setup a 5 node K8s cluster on Ubuntu 16.04

## Your Environment
* Flannel version: "Image": "quay.io/coreos/flannel:v0.10.0-amd64",
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: "Image": "k8s.gcr.io/etcd-amd64:3.1.12",
* Kubernetes version (if used): 1.10
* Docker:
```Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.6.2
 Git commit:   092cba3
 Built:        Thu Nov  2 20:40:23 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
* Operating System and version: Ubuntu 16.04

**Comment by mendoncaangelo** [comment]
Apparently K8s 1.10 was causing the issue. I downgraded to 1.9 and it was fine.

**Comment by benoitheinrich** [comment]
Hi guys, I've got the same issue as documented here, but I can't find how to downgrade my kubernetes version from 1.10 to 1.9.

When running the `sudo kubeadm upgrade apply v1.9.0 --force` command it fails with the following error: 
```
[upgrade/version] FATAL: The --version argument is invalid due to these fatal errors:

	- Specified version to upgrade to "v1.9.0" is equal to or lower than the minimum supported version "v1.10.4". Please specify a higher version to upgrade to
	- Kubeadm version v1.10.4 can only be used to upgrade to Kubernetes versions 1.10

Please fix the misalignments highlighted above and try upgrading again
```

Can you please let me know how to downgrade my kubernetes version, and also, do you know if that issue will be fixed for version 1.10 of kubernetes ?

Thanks.

**Comment by tan-tan-kanarek** [comment]
I'm having the same issue with version 1.11.3, I assume it's not solved yet.
Should I downgrade the server version or the kubectl client version?

**Comment by sunnyguohua** [comment]
I have the same issue when install 3 master in v1.13.4

**Comment by osaffer** [comment]
Hi,

I have this problem because the kubernetes is behind a proxy:

1 main.go:289] Error registering network: failed to acquire lease: node "Hostname" pod cidr not assigned
I0213 09:49:08.307652       1 main.go:366] Stopping shutdownHandler...

In kube-flannel.yml 

I changed the network range.
 "Network": "172.20.0.0/16"

In kube-apiserver.yaml

in Env: section, for value no_proxy, I put this range 172.20.0.0/16
Kubelet was restarted.

But I still the same issue, when I check log
I
kubectl -n kube-system logs -f kube-flannel-ds-amd64-c8q86

I0213 10:01:53.220229       1 vxlan.go:120] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
E0213 10:01:53.220651       1 main.go:289] Error registering network: failed to acquire lease: node "adakub0" pod cidr not assigned
I0213 10:01:53.220775       1 main.go:366] Stopping shutdownHandler...

When I check log for other POD that matches to other node, I see Proxy page.

Thanks in advance,
